### ISSUE TITLE
Overlapping content in listing view on tablet

### ISSUE THREAD

**Issue by PhillippOhlandt** [nestordedios/bolt-theme-solarize#1]
Hey,

when you browse to "All Pages" and bring your browser or the site into a tablet viewport, the text overlaps the image.

You can test it here:
http://solarize.boltthem.es/

**Comment by nestordedios** [comment]
Hey Phillip,

Thanks for telling me. The issue has been fixed in this commit 28b825ab95119bbbe26e23b5bb5f03c17650e84d
and a new release has been created.
